### ISSUE TITLE
CAD model of Beacon revH

### ISSUE THREAD

**Issue by cuiviemen** [beacon3d/docs#2]
Please provide CAD model of Beacon revH. It will help us to adjust/validate existing mount solutions and also create new ones.

**Comment by bbro44** [comment]
I second this

**Comment by mattthebaker** [comment]
Models are added.

New variations are more compact and fit in a smaller space that RevD, most should be close to drop in the existing mounts. Interference with the components, slight shift in the connector locations, or cable escape path are what is most likely to need adjustment.

Guidance on mounting distance remains the same as before.

Some applications of RevD normal may want to switch to RevH low profile for the cable escape.
